import React from 'react'
import FullScreenWrapper from '../../../components/ui/Wrappers/FullScreenWrapper/FullScreenWrapper'
import RandomHeader from '../../../components/ui/Titles/RandomHeader/RandomHeader';
import { useSelector } from 'react-redux';
import { LineSpacer } from '../../../components/ui/Spacers/LineSpacer/LineSpacer';
import { ImageMasonryWrapper } from '../../../components/ui/Wrappers/ImageMasonryWrapper/ImageMasonryWrapper';
import { LongPressGestureWrapper } from '../../../components/ui/Gestures/LongPressGestureWrapper';
import { triggerContext } from '../../../lib/services/helperFunctions';
import { ImageTooltipWrapper } from '../../../components/ui/Wrappers/ImageTooltipWrapper/ImageTooltipWrapper';
import { NsfwWrapper } from '../../../components/ui/Wrappers/NsfwWrapper/NsfwWrapper';
import { ImageComponent } from '../../../components/ui/Image/Image';
import { IconPlaceholder } from '../../../components/ui/Placeholders/IconPlaceholder/IconPlaceholder';
import { Images } from 'lucide-react';
import { BoxLabel } from '../../../components/ui/Titles/BoxLabel/BoxLabel';

export const ServerRecommendations = ({close}) => {

    const galleryHeaders = [
        "A beautifully curated mess, just for you",
        "Not random. Just oddly specific.",
        "Echoes of your collective aesthetic chaos 📡",
        "Generated by taste. Or at least repetition.",
        "Recommendations, synthesized from your strange energy",
        "You post it, we vibe-sort it",
        "Trending… but only within this server"
    ];

    const {server_id } = useSelector(state => state.serverDetailsSlice);

    const {loading, error, mediaByServer} = useSelector(state => state.serverRecommendationsSlice);

    const media = mediaByServer[server_id];
   
    return (
        <FullScreenWrapper onClose={close}>
            <div style={{maxHeight: 'calc(100svh - 10px)', overflowY: 'auto', width: 'calc(100% - 10px)', margin: '0 auto'}}>
                <div style={{
                    display: 'flex',
                    flexDirection: 'column',
                    gap: 5,
                    alignItems: 'flex-start'
                }}>
                <BoxLabel label={'Recommendations'}  />
                <IconPlaceholder icon={Images} />
                <RandomHeader titles={galleryHeaders} />
                </div>
                
                <LineSpacer />
                <ImageMasonryWrapper>
                    {media?.media?.map(media => {
                        return (
                            <LongPressGestureWrapper key={media.src} width={'100%'} height={'100%'} onTouchContext={(e) => triggerContext(e, media.src)}>
                                <ImageTooltipWrapper
                                image={media}

                                >
                                    <NsfwWrapper nsfw={media}>
                                        <ImageComponent src={media?.src?.includes('.gif') ? media?.src : media?.thumbnail}/>
                                    </NsfwWrapper>
                                </ImageTooltipWrapper>
                            </LongPressGestureWrapper>
                        )
                    })}
                </ImageMasonryWrapper>
            </div>
        </FullScreenWrapper>
    )
}
