
import { useSelector } from 'react-redux';
import { ImageMasonryWrapper } from '../../../components/ui/Wrappers/ImageMasonryWrapper/ImageMasonryWrapper';
import { LongPressGestureWrapper } from '../../../components/ui/Gestures/LongPressGestureWrapper';
import { triggerContext } from '../../../lib/services/helperFunctions';
import { NsfwWrapper } from '../../../components/ui/Wrappers/NsfwWrapper/NsfwWrapper';
import { ImageComponent } from '../../../components/ui/Image/Image';
import { Images } from 'lucide-react';
import ScrollLoadWrapper from '../../../components/ui/Wrappers/ScrollLoadWrapper/ScrollLoadWrapper';
import TextLabelError from '../../../components/Error/TextLabelError/TextLabelError';
import ContentHeader from '../../../components/Headers/ContentHeader/ContentHeader';
import { MediaTooltipWrapper } from '../../../components/ui/Wrappers/MediaTooltipWrapper/MediaTooltipWrapper';
import { VideoPreview } from '../../../components/ui/Video/VideoPreview/VideoPreview';

export const ServerRecommendations = ({close}) => {

    const galleryHeaders = [
        "A beautifully curated mess, just for you",
        "Not random. Just oddly specific.",
        "Echoes of your collective aesthetic chaos 📡",
        "Generated by taste. Or at least repetition.",
        "Recommendations, synthesized from your strange energy",
        "You post it, we vibe-sort it",
        "Trending… but only within this server"
    ];

    const {server_id, name } = useSelector(state => state.serverDetailsSlice);

    const {loading, error, mediaByServer} = useSelector(state => state.serverRecommendationsSlice);

    const media = mediaByServer[server_id];
   
    return (
    <ScrollLoadWrapper noMoreItems={true} loading={loading} >
        <ContentHeader Icon={Images} title={`Media Recommendations For ${name}`} subTitle={galleryHeaders[Math.floor(Math.random() * galleryHeaders.length)]} />
        <TextLabelError error={error} />
        <ImageMasonryWrapper>
            {media?.media?.map(media => {
                return (
                    <LongPressGestureWrapper key={media.src} width={'100%'} height={'100%'} onTouchContext={(e) => triggerContext(e, media.src)}>
                        <MediaTooltipWrapper media={media} >
                            <NsfwWrapper nsfw={media}>
                                {media.type === 'video' ? 
                                <VideoPreview {...media} action={() => {}} />
                                :
                                <ImageComponent borderRadius={'var(--border-radius)'} src={media?.src?.includes('.gif') ? media?.src : media?.thumbnail}/>
                                }
                            </NsfwWrapper>
                        </MediaTooltipWrapper>
                    </LongPressGestureWrapper>
                )
            })}
        </ImageMasonryWrapper>

    </ScrollLoadWrapper>)
}
